name: Morefeatures
version: ${project.version}
main: io.github.chenjj100419.morefeatures.morefeatures.Morefeatures
api-version: 1.16
authors: [chenjj100419]
description: ThePluginsAddForfeatures
website: chenjj100419.github.io/WebBlogHtml
